server {
    listen 80;
    server_name localhost 127.0.0.1 local.bibutong.com;

    location / {
        proxy_pass http://bibutong-front;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        expires -1;
    }

    # 暂时注释后端与AI，避免启动时解析失败
    location /api/ {
        proxy_pass http://bibutong-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,OPTIONS always;
        if ($request_method = 'OPTIONS') { return 204; }
    }

    location /ai/vector/ {
        proxy_pass http://llama:8000/vector/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}